spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5445/authentication_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

application:
  security:
    jwt:
      access-token:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        expiration: 240000 # a 4 minutes
      refresh-token:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        expiration: 604800000 # 7 days
  http:
    auth-header-name: 'Authorization'
    auth-header-start: 'Bearer '
    refresh-token-name: 'refresh_token'
