spring:
  application:
    name: api-gateway-service
  cloud:
    config:
      enabled: false



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: info
    org.springframework.cloud:
      gateway: trace
      gateway.route.RouteDefinitionLocator: info
