spring:
  application:
    name: user-management-service
  data:
    mongodb:
      host: users_db
      port: 27018
      database: users_db

rabbitmq:
  queue:
    user-creation: user-management-creation-queue
  exchange: internal.exchange
  routing-key:
    user-management:
      user-creation: user-management-creation
    username-change: username-change



server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

application:
  security:
    jwt:
      access-token:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  http:
    auth-header-start: 'Bearer '
