spring:
  application:
    name: chat-support-service
  data:
    mongodb:
      host: chats_db
      port: 27017
      database: chats_db

rabbitmq:
  queue:
    user-creation: chat-support-creation-queue
    username-change: chat-support-change-username-queue
  exchange: internal.exchange
  routing-key:
    chat-support:
      user-creation: chat-support-creation
    username-change: username-change

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


application:
  security:
    jwt:
      access-token:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  http:
    auth-header-name: 'Authorization'
    auth-header-start: 'Bearer '

