version: '3'
services:

  users_db:
    image: mongo:5.0
    container_name: users_db
    restart: always
    ports:
      - "27018:27017"

  authentication_db:
    image: postgres:13
    container_name: authentication_db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: authentication_db
    ports:
      - "5445:5432"

  chats_db:
    image: mongo:5.0
    container_name: chats_db
    restart: always
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3.12.2
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
