version: '3'
services:
  users_db:
    image: postgres:13
    container_name: users_db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: users_db
    ports:
      - "5444:5432"

  authentication_db:
    image: postgres:13
    container_name: authentication_db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: authentication_db
    ports:
      - "5445:5432"

  chats_db:
    image: mongo:5.0
    container_name: chats_db
    restart: always
    ports:
      - "27017:27017"
