package ru.gusarov.messenger.util.dto.errors.logic;

public enum ErrorCode {
    INVALID_REQUEST_PATH,
    EMAIL_IS_OCCUPIED,
    USERNAME_IS_OCCUPIED,
    USER_NOT_FOUND,
    USER_IS_NOT_ENABLED, INVALID_USERNAME_PASSWORD, NO_RIGHT_TO_CHANGE, MESSAGE_NOT_FOUND, NOT_AUTHORIZED, TOKEN_NOT_FOUND, CHAT_NOT_FOUND,

}